finance/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.base_page, name='base_page'),
    url(r'^accounts/$', views.create_account, name='create_account'),
    url(r'^accounts/(?P<account_id>\d+)/$', views.create_charge, name='create_charge' ),
]

myfinance/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('finance.urls', namespace='finance')),
]

finance/models.py
from django.db import models

# Create your models here.
class Acount(models.Model):
    name = models.CharField(max_length=16)
    number = models.CharField(max_length=19, help_text='Enter format: XXXX XXXX XXXX XXXX')
    amount = models.DecimalField(decimal_places=2, default=0, max_digits=300)

class Charge(models.Model):
    transaction = models.DecimalField(decimal_places=2, max_digits=300)
    dat = models.DateField()
    account = models.ForeignKey(Acount, related_name='charge')

finance/forms.py
from django import forms
from datetime import date
import re
from .models import Acount, Charge

class AcountForm(forms.ModelForm):
    
    class Meta:
        model = Acount
        fields = ('name', 'number')

    def clean(self):
        #CREDIT_CARD_VALID = r'^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\d{11})$'
        number = self.cleaned_data.get('number')
        #number = number.replace(' ', '').replace('-', '')
        number = number.replace(' ', '')
        #if not re.match(CREDIT_CARD_VALID, number):
        if len(number) != 16:    
            self.add_error(
                'number', "Card number you specified is not valid.")
        self.cleaned_data['number'] = number
        return self.cleaned_data

class ChargeForm(forms.ModelForm):

    class Meta:
        model = Charge
        fields = ('transaction', 'dat')    
    def clean(self):
        cleaned_data = super(ChargeForm, self).clean()
        transaction = cleaned_data.get('transaction')
        dat = cleaned_data.get('dat')
        if transaction == 0 or transaction is None:
            self.add_error('transaction', "Transaction can't equal zero")
        if transaction < 0 and dat > date.today():
            self.add_error('transaction', "Invalid transaction")
        return cleaned_data

finance/views.py
from django.shortcuts import render
from .forms import AcountForm, ChargeForm
from .models import Acount, Charge

# Create your views here.

def base_page(request):
    return render(request, 'main.html')

def create_account(request):
    if request.method == "POST":
        form = AcountForm(request.POST)
        if form.is_valid():
            form.save()
            form = AcountForm()
            return render(request, 'accounts.html', {'form':form, 'lst_account': Acount.objects.all()})
        else:
            pass
    else:
        form = AcountForm()
    return render(request, 'accounts.html', {'form':form, 'lst_account': Acount.objects.all()})

def create_charge(request, account_id):
    if request.method == "POST":
        form = ChargeForm(request.POST)
        if form.is_valid():
            charge = form.save(commit=False) #пока в базу не сохранякем
            charge.account = Acount.objects.get(id=account_id)
            account = Acount.objects.get(id=account_id)
            account.amount += charge.transaction
            account.save()
            charge.save()
            form = ChargeForm()
            return render(request, 'charges.html', {'form':form, 'lst_charges': Charge.objects.filter(account=account_id)})
        else:
            pass
    else:
        form = ChargeForm()
    return render(request, 'charges.html', {'form':form, 'lst_charges': Charge.objects.filter(account=account_id)})

finance/templates/accounts.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Homework_5_Serebryakov_Alex</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/finance.css' %}">
    </head>
    <body>
        <p><a href="/">To main page</a></p>                
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
        <button type="submit">Submit</button>
        </form>
        {%if lst_account %}
        <table border="1">
            <caption>Your accounts:</caption>
            <tr>
                <th>Account name</th>
                <th>Amount</th>
                <th>Create charge</th>
            </tr>
        {% for i in lst_account %}
            <tr>
                <td>{{i.name}}</td>
                <td>{{i.amount}}</td>
                <td><form action={% url 'finance:create_charge' i.id %}><button type="submit">create charge</button></form>
            </tr>
           {% endfor %}
        </table>
        {% else %}
        <p>No accounts yet, create account</p>
        {% endif %}
    </body>
</html>   

finance/templates/charges.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Homework_5_Serebryakov_Alex</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/finance.css' %}">
    </head>
    <body>
        <p><a href="/">To main page</a></p>
        <p><a href="/accounts/">To accounts</a></p>                
        <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
        <button type="submit">Submit</button>
        {% if lst_charges %}
         <table border="1">
            <caption>Your charges:</caption>
            <tr>
                <th>Charge</th>
                <th>Date</th>
            </tr>
        {% for i in lst_charges %}
            <tr>
                <td>{{i.transaction}}</td>
                <td>{{i.dat}}</td>
            </tr>
           {% endfor %}
        </table>
        {% else %}
        <p>No charges yet, add charge</p>
        {% endif %}
    </body>
</html> 

finance/templates/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>Homework_5_Serebryakov_Alex</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/finance.css' %}">
    </head>
    <body>
        <h2>Welcome!</h2>
        <h4>Homework_5_Serebryakov_Alex</h4>
        <p><a href='/accounts/'>To your accounts</a></p>
    </body>
</html>   